### ISSUE TITLE
Authorship Chapter is Missing

### ISSUE THREAD

**Issue by jdbean** [google/opencasebook#2]
The [Authorship](https://opensource.google.com/docs/casebook/authorship/#) chapter does not appear in this repository. Would it be possible to add the markdown source please?

**Comment by sillsm** [comment]
Hi! Sure let me get on it.

**Comment by sillsm** [comment]
Done. You may notice the internal seems out of sync with external, but this is the copy that will be public shortly. We added Tasini to round out discussing collective works.

**Comment by jdbean** [comment]
@sillsm Thanks!
